# -*- coding: utf-8 -*-
"""DFUtilities

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gc6gE9xX0SdqImmRk7QNS8eofQOMps81
"""

import numpy as np
import pandas as pd

class dfUtil():

  def __init__(self):
    self.df1 = ""
    self.df2 = ""
    self.log = []

  def load_data(self,train_path,test_path):
      self.df1 = pd.read_csv(train_path,on_bad_lines='skip')
      if test_path != '':
        self.df2 = pd.read_csv(test_path,on_bad_lines='skip')

  def get_lengths(self,test_path):
    self.log.append("Length of Train Dataset : " + str(len(self.df1)))
    if test_path == "":
      self.log.append("No Test Dataset Provided")
    else:
      self.log.append("Length of Test Dataset : " + str(len(self.df2)))

  def check_for_nulls(self):
    df_list = [self.df1,self.df2]
    df_names = ['Train Dataset', "Test Dataset"]
    for i,df in enumerate(df_list):
      self.log.append("Number of Null Values in " + df_names[i] + " : " + str(df.isnull().sum()[0]))

  def handle_data(self,path1,path2):
    self.load_data(path1,path2)
    self.get_lengths(path2)
    self.check_for_nulls()
    return self.df1,self.df2,self.log